INSERT INTO "MEMBER"
(MEMBER_ID, MEMBER_LOGINID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_PHONENUMBER, MEMBER_BIRTH, MEMBER_REGDATE, MEMBER_DEL, MEMBER_ADDRESS, MEMBER_EMAIL)
VALUES((SELECT NVL(MAX(MEMBER_ID),0) FROM "MEMBER" m)+1 , 'admin', '1234', 'admin', 'admin', '010-1111-1111', '2022-02-12', SYSDATE, 'N'	, 'GOODEE', 'aaa@naver.com');

-- INSERT INTO COUPON 
-- (COUPON_ID, COUPON_NAME, COUPON_DISCOUNT, COUPON_SDATE, COUPON_SDATE)
-- VALUES((SELECT NVL(MAX(COUNPON_ID),0) FROM COUNPON)+1) , '20%COUPON', '20', '2022-0101', '2022-1231');

SELECT * FROM COUPON ;

SELECT *
	FROM "MEMBER" m 
	WHERE MEMBER_LOGINID = 'admin'
	AND MEMBER_PASSWORD = '1234' ;
	
SELECT MEMBER_NAME , MEMBER_NICKNAME , MEMBER_PHONENUMBER , MEMBER_BIRTH , MEMBER_REGDATE , MEMBER_ADDRESS , MEMBER_EMAIL 
	FROM "MEMBER" m ;
	
DROP TABLE "MEMBER" ;
DROP TABLE COUPON ;
DROP TABLE MEMBER_COUPON ;
DROP TABLE PRODUCT ;
DROP TABLE "ORDER" ;
DROP TABLE ORDER_DETAIL ;
DROP TABLE QNA ;
DROP TABLE "QNA-C" ;
DROP TABLE ADMIN ;
DROP TABLE BOARD ;
DROP TABLE CART_ITEM ;
DROP TABLE CART_ORDER ;