SELECT *
	FROM PRODUCT
	ORDER BY PRODUCT_ID ;
	
SELECT  PRODUCT_NAME , PRODUCT_PRICE ,PRODUCT_INVENTORY ,
		PRODUCT_DETAIL , PRODUCT_SOLD , PRODUCT_REGDATE 
	FROM (SELECT ROWNUM, PRODUCT_NAME , PRODUCT_PRICE ,PRODUCT_INVENTORY ,
		PRODUCT_DETAIL , PRODUCT_SOLD , PRODUCT_REGDATE 
	FROM PRODUCT p
	ORDER BY PRODUCT_ID DESC)
	WHERE ROWNUM <=5 ;
	